config/routes.rb
Site704home::Application.routes.draw do
  get "coupons/create"

	devise_for :admin_users, ActiveAdmin::Devise.config
	ActiveAdmin.routes(self)

	devise_for :users,
	path: "",
	path_names: {
		sign_in: "login",
		sign_out: "logout",
	},
	controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"  }

	resources :product_categories, only: [:index, :show], path: 'categorias'
	resources :ambients, only: [:index, :show], path: 'ambientes' do
		resources :sub_ambients, only: [:show], path: 'subambientes'
	end

	resources :users, only: [], path: 'usuarios' do
		member do
			get 'cart', controller: 'carts', action: 'show', path: 'carrinho'
			get 'carts', controller: 'carts', action: 'index', path: 'pedidos'
			# get 'payments', controller: 'payments', action: 'index', path: 'pagamentos'
		end
	end

	resources :payments, only: [:new, :create], path: 'pagamentos'
	resources :payment_notifications, only: [:create], path: 'notificacoes_de_pagamento'

	resources :newsletters, only: [:create]

	# resources :magazines, only: [:show, :index], path: 'revistas'
	resources :magazines, only: [:show], path: 'revistas'

	resources :products, only: [], path: 'busca' do
		collection do
			get 'search'
			get 'color_search'
		end
	end

	resources :color_products, only: [:show], path: 'produtos' do
		resources :cart_color_products, only: [:index, :create, :update, :destroy]
	end

	resources :post_categories, only: [:show]
	resources :posts, only: [:show]

	resources :year, only: [] do
		resources :month, only: [] do
			resources :calendar, only: [:show]
		end
	end

	resources :architects, only: [:show, :index], path: 'arquitetos'

	resources :carts, only: [:show], path: 'carrinho' do
		member do
			resources :coupons, only: [:create], path: 'cupons'
		end
	end

	get 'quem_somos', controller: 'static_pages', action: 'about', path: 'quem_somos', as: :about
	get 'termos_de_privacidade', controller: 'static_pages', action: 'privacy', path: 'termos_de_privacidade', as: :privacy
	get 'politica_de_troca', controller: 'static_pages', action: 'trade', path: 'politica_de_troca', as: :trade
	get 'clube', controller: 'static_pages', action: 'club', path: 'clube', as: :club
	get 'faq', controller: 'static_pages', action: 'faq', path: 'faq', as: :faq
	get 'regulamento_promocional', controller: 'static_pages', action: 'promotion_rules', as: :promotion_rules

	match 'contact' => 'contact#create', as: :contact, via: :post
	resource :comments, only: [:create]

	resources :collections, only: [:show], path: 'colecoes'

	resources :multibrands, only: [:new, :create], path: 'multimarcas'
	resources :b2bs, only: [:new, :create], path: 'b2b'
	resources :presses, only: [:index, :show], path: '704-na-midia'

	# resources :magazine_pages, only: [:create]

	root to: 'static_pages#home'
	# root to: 'static_pages#building'
	match 'home' => 'static_pages#home', as: :home, via: :get

	get 'sitemap' => 'sitemap#index', as: :sitemap

	get 'obrigado' => 'static_pages#home', as: :thanks, via: :get

	resources :shipping, only: [:create], controller: 'carts/shipping'

	namespace :api do
		namespace :v1 do
			resources :products, only: [:create, :update, :index, :show]
			resources :colors, only: [:create, :update, :index, :show]
			resources :color_products, only: [:create, :update, :index, :show]
			resources :payments, only: [:index, :show] do
				member do
					put 'sync'
					put 'set_shipping_code'
				end
				collection do
					get 'no_shipping_code'
				end
			end
		end
	end
end

app/controllers/static_pages_controller.rb
# encoding: UTF-8

class StaticPagesController < ApplicationController
  def about
    @title = "Quem somos"
    @content = ExtraInfo.first.about
    # render 'static_pages/pure_text'
  end

  def privacy
    @title = "Segurança e Privacidade"
    @content = ExtraInfo.first.privacy_terms
    render 'static_pages/pure_text'
  end

  def promotion_rules
    @title = "Regulamento Promocional"
    render 'static_pages/pure_text'
  end

  def trade
    @title = "Política de Troca"
    @content = ExtraInfo.first.trade_terms
    render 'static_pages/pure_text'
  end

  def club
    @title = "Clube 704 Home"
    @content = ExtraInfo.first.club_704
    # @insta_photos = HTTParty.get('https://api.instagram.com/v1/users/543317433/media/recent?count=60&access_token=543317433.1fb234f.d943d2c4c6bf412287f3c3e9daa7bafe')['data']
    @insta_photos = HTTParty.get('https://api.instagram.com/v1/tags/clube704home/media/recent?access_token=543317433.1fb234f.d943d2c4c6bf412287f3c3e9daa7bafe')['data']
    render 'static_pages/pure_text'
  end

  def faq
    @faqs = Faq.all
  end

  def home
    @products = Product.where(spotlight: true).joins(color_products: :color_product_photos).uniq.sample(8)

    @magazine_products = @products.first(4).map { |x| x.color_products.includes(:product).includes(:colors).sample(1).first }
    @products = @products.last(4)

    # @magazine = Magazine.includes(:magazine_pages).includes(magazine_pages: :references).includes(magazine_pages: { references: :product }).last
    # @magazine_products = Reference.includes(:product).where(magazine_page_id: MagazinePage.where(magazine_id: @magazine.id)).joins(product: { color_products: :color_product_photos }).map { |x| x.product }.sample(4)
   #  @magazine_products = @magazine.magazine_pages.map { |x| x.references }.flatten.uniq.map { |x| x.color_product }.uniq.sample(4)

    @architect = Architect.all.reject { |x| x.posts.where("date < ?", DateTime.now).empty? }.map { |x| x.posts.last }.sort_by { |x| x.date }.last.architect
    @architect = Architect.joins(:posts).where("posts.date < ?", DateTime.now).order("posts.date ASC").last


    @color_products = @products.map { |x| x.color_products.includes(:product).includes(:colors).sample(1).first }

    if @products.length < 4
      Product.joins(color_products: :color_product_photos).all.uniq.sample(4 - @products.length).each do |prod|
        @products.push prod
      end
    end

  	@post_diy = PostCategory.find_by_name('DIY').posts.where("date < ?", DateTime.now).last
  	@post_inspirese = PostCategory.find_by_name('Inspire-se').posts.where("date < ?", DateTime.now).last

    # @banner = Banner.where(active: true).last
    @banners = Banner.where(active: true)

    if request.path == thanks_path
      @payment = Payment.find params[:p]
      if @payment
        @thanks = request.path == thanks_path
      end
    end
  end

  def building
    render 'static_pages/building', layout: false
  end
end

app/views/static_pages/about.html.haml
- title(@title, true)

.row
  .title= @title.mb_chars.upcase.to_s
%hr

.about
  .row
    .columns.grid7.photo1
      = image_tag "quemsomos1.jpg"
    .columns.grid5.column1
      = @content.html_safe
  .row
    .columns.grid5.column2
    .columns.grid7.photo2
      = image_tag "quemsomos2.jpg"

app/views/static_pages/building.html.haml
%h1 EM CONSTRUÇÃO

app/views/static_pages/faq.html.haml
- title("FAQ", true)

.row
	.title PERGUNTAS FREQUENTES
%hr

.row.accordion#accordion2
	- @faqs.each_with_index do |faq, i|
		.accordion-group
			.accordion-heading
				= link_to faq.question, "#collapse#{i}", data: { toggle: 'collapse', parent: '#accordion2' }, class: "accordion-toggle title"
			.accordion-body.collapse.out{id: "collapse#{i}"}
				.accordion-inner
					= faq.answer.html_safe

app/views/static_pages/home.html.haml
.home_page
	.row.magazine_part
		.columns.grid7
			-# .home_magazine
			-# 	= link_to Magazine.last do
			-# 		= image_tag @magazine.magazine_pages.first.photo
			#homeCarousel.carousel.slide
				%ol.carousel-indicators
					- (0..(@banners.length - 1)).each do |i|
						%li{ class: ('active' if i == 0), data: { target: '#homeCarousel', :'slide-to' => i.to_s } }
				.carousel-inner
					- @banners.each_with_index do |banner, i|
						.item{ class: ('active' if i == 0) }
							= link_to banner.url do
								= image_tag banner.image.url(:carousel)
				= link_to "&lsaquo;".html_safe, '#homeCarousel', class: 'carousel-control left', data: { slide: 'prev' }
				= link_to "&rsaquo;".html_safe, '#homeCarousel', class: 'carousel-control right', data: { slide: 'next' }
		.columns.grid5
			- @magazine_products.each_with_index do |prod, i|
				- if i%2 == 0
					- thumb_style = "float: left;"
					- info_style = "float: right;"
				- else
					- my_style = "float: right;"
					- info_style = "float: left;"
				.product_thumb
					- url = color_product_path(id: prod.slug)
					.info{style: info_style}
						.title
							= prod.product.name.mb_chars.upcase.to_s
						- desc = prod.product.magazine_description
						- desc = prod.product.description if desc.blank?
						- unless desc.nil?
							.description_content
								= desc.html_safe
						= link_to "Saiba mais", url, class: 'more'
					.position{style: my_style}
						= link_to url do
							.photo
								= image_tag prod.photo.photo.url(:home_thumb)
							.overlay
								.over
									.whitefill
									= link_to url, class: 'bt details' do
										%span.icon.icon-plus
									- unless prod.stock_ammount < 1
										= link_to color_product_cart_color_products_path(prod.id), method: :post, remote: true, class: 'bt add_to_cart' do
											%span.icon.icon-shopping-cart
							.price
								%span= "#{prod.product.parcels}x"
								= number_to_currency prod.product.price / prod.product.parcels
				- unless i == @magazine_products.length - 1
					%hr
		- if @banner
			.banner-right
				= link_to image_tag(@banner.image), @banner.url
				/ = link_to image_tag("BANNERALMOFADAScompl.gif"), "http://www.704home.com.br/categorias/capas-de-almofada"

	.row.ambients_part
		.row.title
			DESTAQUES
			= link_to product_categories_path, class: 'all_posts' do
				ver produtos
				.icon-area
					.icon.icon-th
		%hr
		= render 'shared/columns', my_array: @products.map { |x| x.color_products.includes(:product).includes(:colors).sample(1).first }, item_path: :product_category,  partial_path: 'products/shared/product_thumb', n: 4, total_columns: 12, description: true, no_pagination: true
	.row.blog_part
		.grid4.columns
			.row.title
				INSPIRE-SE
				= link_to PostCategory.find_by_name('Inspire-se'), class: 'all_posts' do
					ver posts
					.icon-area
						.icon.icon-align-justify
			%hr
			.row.blog_info
				.content= @post_inspirese.content.html_safe
				= link_to "Continuar lendo", @post_inspirese, class: 'more'
				- if @post_inspirese.media_type == "Foto"
					= image_tag @post_inspirese.photo.url(:thumb)
				- else
					%iframe{width: "311", height: "311", src: @post_inspirese.media_link, frameborder: "0", allowfullscreen: nil}
		.grid4.columns.diy
			.row.title
				DIY
				= link_to PostCategory.find_by_name('DIY'), class: 'all_posts' do
					ver posts
					.icon-area
						.icon.icon-align-justify
			%hr
			.row.blog_info
				.content= @post_diy.content.html_safe
				= link_to "Continuar lendo", @post_diy, class: 'more'
				- if @post_diy.media_type == "Foto"
					= image_tag @post_diy.photo.url(:thumb)
				- else
					%iframe{width: "311", height: "311", src: @post_diy.media_link, frameborder: "0", allowfullscreen: nil}
		.grid4.columns.arch
			.top
				= link_to club_path, class: "club" do
					.row.title CLUBE 704 HOME
					%hr
					.row.club_704
						%p QUER FAZER PARTE DO NOSSO CLUBE?
						%p Siga o instagram @704home, poste sua foto com #clube704home.
						%p As melhores fotos, com os ambientes mais criativos e bonitos serão selecionadas e entrarão no nosso Blog quinzenalmente. Participe!
			.bottom
				.row.title
					TOQUES DOS EXPERTS
					= link_to architects_path, class: 'all_posts' do
						ver posts
						.icon-area
							.icon.icon-align-justify
				%hr
				.row.architect_info
					= link_to @architect do
						.photo= image_tag @architect.photo.url(:thumb)
						.content= @architect.posts.last.content.html_safe
						.more= "Continuar lendo"

app/views/static_pages/pure_text.html.haml
- title(@title, true)

.row
  .title= @title.mb_chars.upcase.to_s
%hr

.row.just_text
  - if request.path == promotion_rules_path
    %p O dia do amigo está chegando e nada melhor do que fazer uma grande homenagem para quem está do seu lado sempre, em todas as horas da sua vida!
    %p Então, mande para a gente a melhor frase que define a amizade de vocês, junto com o nome e uma foto de vocês até o dia 19/07/2015.
    %p A melhor homenagem aparecerá em todas as nossas redes sociais – facebook, instagram e pinterest – e ainda ganhará duas duplas do jogo americano Collage, que quando colocadas juntas, formam um lindo circulo, que representa exatamente a amizade!
    %p E tem mais: Os ganhadores receberão uma consultoria gratuita de como deixar a casa arrumada, sem gastar muito!
    %P Vocês ainda terão motivos de sobra para se reunir para comer uma pizza, um fondue, tomar um bom vinho ou, simplesmente, beber um chopp com petiscos, em grande estilo!
  - else
    = @content.html_safe

- if @insta_photos.present?
  .row.insta-photos
    - urls = []
    - big_urls = []
    - @insta_photos.each do |p|
      - tags = ['clube704home']
      - tags.each do |t|
        - if p['tags'].include? t and not urls.include? p['images']['low_resolution']['url'] and urls.length < 8
          - urls.push p['images']['low_resolution']['url']
          - big_urls.push p['link']

    .grid12
      - counter = -1
      - urls.each_slice(4) do |group|
        - counter += 1
        .row
          - group.each_with_index do |url, i|
            .columns.grid3
              = link_to big_urls[(counter*4) + i], target: '_blank' do
                = image_tag url
                .overlay-area