config/routes.rb
Site704home::Application.routes.draw do
  get "coupons/create"

	devise_for :admin_users, ActiveAdmin::Devise.config
	ActiveAdmin.routes(self)

	devise_for :users,
	path: "",
	path_names: {
		sign_in: "login",
		sign_out: "logout",
	},
	controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"  }

	resources :product_categories, only: [:index, :show], path: 'categorias'
	resources :ambients, only: [:index, :show], path: 'ambientes' do
		resources :sub_ambients, only: [:show], path: 'subambientes'
	end

	resources :users, only: [], path: 'usuarios' do
		member do
			get 'cart', controller: 'carts', action: 'show', path: 'carrinho'
			get 'carts', controller: 'carts', action: 'index', path: 'pedidos'
			# get 'payments', controller: 'payments', action: 'index', path: 'pagamentos'
		end
	end

	resources :payments, only: [:new, :create], path: 'pagamentos'
	resources :payment_notifications, only: [:create], path: 'notificacoes_de_pagamento'

	resources :newsletters, only: [:create]

	# resources :magazines, only: [:show, :index], path: 'revistas'
	resources :magazines, only: [:show], path: 'revistas'

	resources :products, only: [], path: 'busca' do
		collection do
			get 'search'
			get 'color_search'
		end
	end

	resources :color_products, only: [:show], path: 'produtos' do
		resources :cart_color_products, only: [:index, :create, :update, :destroy]
	end

	resources :post_categories, only: [:show]
	resources :posts, only: [:show]

	resources :year, only: [] do
		resources :month, only: [] do
			resources :calendar, only: [:show]
		end
	end

	resources :architects, only: [:show, :index], path: 'arquitetos'

	resources :carts, only: [:show], path: 'carrinho' do
		member do
			resources :coupons, only: [:create], path: 'cupons'
		end
	end

	get 'quem_somos', controller: 'static_pages', action: 'about', path: 'quem_somos', as: :about
	get 'termos_de_privacidade', controller: 'static_pages', action: 'privacy', path: 'termos_de_privacidade', as: :privacy
	get 'politica_de_troca', controller: 'static_pages', action: 'trade', path: 'politica_de_troca', as: :trade
	get 'clube', controller: 'static_pages', action: 'club', path: 'clube', as: :club
	get 'faq', controller: 'static_pages', action: 'faq', path: 'faq', as: :faq
	get 'regulamento_promocional', controller: 'static_pages', action: 'promotion_rules', as: :promotion_rules

	match 'contact' => 'contact#create', as: :contact, via: :post
	resource :comments, only: [:create]

	resources :collections, only: [:show], path: 'colecoes'

	resources :multibrands, only: [:new, :create], path: 'multimarcas'
	resources :b2bs, only: [:new, :create], path: 'b2b'
	resources :presses, only: [:index, :show], path: '704-na-midia'

	# resources :magazine_pages, only: [:create]

	root to: 'static_pages#home'
	# root to: 'static_pages#building'
	match 'home' => 'static_pages#home', as: :home, via: :get

	get 'sitemap' => 'sitemap#index', as: :sitemap

	get 'obrigado' => 'static_pages#home', as: :thanks, via: :get

	resources :shipping, only: [:create], controller: 'carts/shipping'

	namespace :api do
		namespace :v1 do
			resources :products, only: [:create, :update, :index, :show]
			resources :colors, only: [:create, :update, :index, :show]
			resources :color_products, only: [:create, :update, :index, :show]
			resources :payments, only: [:index, :show] do
				member do
					put 'sync'
					put 'set_shipping_code'
				end
				collection do
					get 'no_shipping_code'
				end
			end
		end
	end
end

app/views/shared/_calendar.html.haml
%table{data: { year: year.to_i, month: month.to_i }}
	%tr
		%th D
		%th S
		%th T
		%th Q
		%th Q
		%th S
		%th S
	- first_day = DateTime.new(year.to_i, month.to_i)
	- dif = (first_day - first_day.beginning_of_week.yesterday).to_i
	- dif = 0 if dif == 7
	- (0..dif + Time.days_in_month(month.to_i, year.to_i) - 1).each_slice(7) do |s|
		%tr
			- s.each do |i|
				- if i < dif
					%td
				- else
					- n = i - dif + 1
					- if current_date.present? and n == current_date
						%td.current= n
					- else
						- architect_id ||= nil
						- if DateTime.new(year.to_i, month.to_i, n) <= Date.current
							- day_posts = Post.where(architect_id: architect_id, post_category_id: post_category_id).select { |x| x.date.year == year.to_i and x.date.month == month.to_i and x.date.day == n }
							- if day_posts.present?
								%td
									= link_to n, day_posts.first
							- else
								%td= n
						- else
							%td= n

app/views/shared/_columns.html.haml
- no_pagination ||= false

- unless no_pagination
  = paginate my_array

- ambient_area ||= false
- description ||= false
- my_array.each_slice(n) do |items|
  .row
    - items.each do |item|
      .columns{class: "grid#{12/n}"}
        = render partial_path, item.class.to_s.downcase.to_sym => item, item_path: item_path, description: description, ambient_area: ambient_area

- unless no_pagination
  = paginate my_array

app/views/shared/_comment.html.haml
- unless @current_comments.empty?
	.old_comments_area
		.comments_title COMENTÁRIOS
		- @current_comments.each do |comment|
			.title= comment.name
			.comment_content= comment.content
			%hr

.new_comments_area
	.comments_title DEIXE SEU COMENTÁRIO
	= semantic_form_for Comment.new, remote: true do |f|
		.inline_inputs
			= f.input :name, label: false, placeholder: "digite seu nome", class: 'teste'
			= f.input :email, label: false, placeholder: "digite seu e-mail"
		= f.input :content, label: false, placeholder: "digite seu comentário"
		= f.input :url, as: :hidden, value: request.path
		= f.action :submit, label: "Comentar".mb_chars.upcase.to_s
.commented_message
	%p= "Obrigado pelo comentário."

app/views/shared/_errors.html.haml
- errors.each do |attribute, msg|
	= content_tag :div, "#{attribute} #{msg}", :class => "flash_message flash_error"

app/views/shared/_footer.html.haml
.footer
	.row
		.column.grid4
			.title= 'CONTATO'
			%hr
			.contact
				= form_for EmailMessage.new, url: contact_path do |f|
					= f.text_field :name, placeholder: 'digite seu nome'
					= f.text_field :email, placeholder: 'digite seu e-mail'
					= f.text_area :body, placeholder: 'digite sua mensagem'
					= f.submit "ENVIAR"
		.column.grid4.offset4
			.title= 'DEPOIMENTOS'
			.testimonial
				%hr
				- Testimonial.all.sample(3).each do |t|
					.test_content= "\"#{t.content}\""
					.test_author= t.name
	.row
		.column.grid4.multibrand
			= link_to new_multibrand_path, class: 'column grid4 multibrand' do
				.title= 'MULTIMARCAS'
				%hr
				%p= ExtraInfo.first.multibrand.html_safe
		.column.grid4.offset4.sitemap
			.title= 'MAPA DO SITE'
			%hr
			.links_left
				= link_to "Quem somos", about_path
				= link_to "Ambientes", ambients_path
				= link_to "Inspire-se", PostCategory.find_by_name('Inspire-se')
				= link_to "DIY", PostCategory.find_by_name('DIY')
				= link_to "Toques dos Experts", architects_path
				-# = link_to "Revista 704 NOW", Magazine.last
				= link_to "Regulamento Promocional", promotion_rules_path
			.links_right
				= link_to "Clube 704 Home", club_path
				- if Press.count > 0
					= link_to "704 na Mídia", presses_path
				= link_to "B2B", new_b2b_path
				= link_to "Política de Troca", trade_path
				/ = link_to "Onde Comprar", '#'
				= link_to "Seguranças e Privacidade", privacy_path
				= link_to "FAQ", faq_path
				/ = link_to "Glossário", '#'
	.row.endereco= "#{ExtraInfo.first.address}".mb_chars.upcase.to_s
	.row.endereco{ style: "margin-top: 0" }= "#{ExtraInfo.first.phone}".mb_chars.upcase.to_s
.fullsizewhite
	= "Todos os direitos direitos reservados #{ExtraInfo.first.business_name} - #{DateTime.now.year} | CNPJ: #{ExtraInfo.first.cnpj}"
	#siteseal
		%script{src: "https://seal.godaddy.com/getSeal?sealID=tOnguwzLAK5BItmqZzbfuAEmel0THQM3dSRPLtIgNBhmQLRZp8fZoSGPXon", type: "text/javascript"}

app/views/shared/_header.html.haml
.row
	.pull-right.secondary-login-links
		- if user_signed_in?
			.logged-in
				%span.icon-user
				%p.inline-block= "Olá, "
				%p.inline-block.bold= "#{current_user.name.mb_chars.upcase.to_s}"
				.header_logged_links_box
					= link_to "EDITAR", edit_user_registration_path, class: 'modal-render-link', remote: true, id: 'edit_account_link', data: { width: "400px" }
					%p.inline-block= "|"
					= link_to "SAIR", destroy_user_session_path, method: :delete
		- else
			= link_to "esqueci minha senha", new_user_password_path, class: 'inline-block modal-render-link', remote: true, id: 'forgot_password_link'
			%p.inline-block= "|"
			= link_to "CADASTRO", new_user_registration_path, class: 'inline-block bold modal-render-link', remote: true, id: 'sign_up_link'
.row
	.pull-left.align-bottom
		= simple_form_for Newsletter.new, remote: true, html: { class: 'form-inline inline-block'} do |f|
			.input-append
				= f.email_field :email, placeholder: 'digite seu email e receba nossa newsletter'
				= button_tag type: 'submit', class: 'append' do
					%span.icon-envelope
	.pull-right.align-bottom
		- if user_signed_in?
			.logged-in
				.menu-row
					%ul
						= hidden_field_tag :current, '-1'
						%li
							%span.icon.icon-truck
							= link_to "Meus Pedidos", carts_user_path(current_user)
						%li
							= link_to cart_path(current_cart), class: 'cart-link-logged-in' do
								%span.icon.icon-shopping-cart
								Carrinho
								%span.cart-totals= "#{current_cart.total_items} ite#{current_cart.total_items == 1 ? 'm' : 'ns'}"
		- else
			= simple_form_for 'user', url: user_session_path, html: { class: 'form-inline inline-block' }, remote: true, format: :json, data: { flash: 'modal' } do |f|
				= f.email_field :email, placeholder: "digite seu e-mail"
				.input-append
					= f.password_field :password, placeholder: "digite sua senha"
					= button_tag type: 'submit', class: 'append' do
						%span.icon-lock
			= link_to '#', class: 'inline-block facebook-login', data: { link: user_omniauth_callback_path('facebook') } do
				%p Conectar
				%span.icon-facebook
			= link_to cart_path(current_cart), :class => 'cart-link-not-logged' do
				%span.icon.icon-shopping-cart
				%span.cart-link-title Carrinho
				%span.cart-totals= "#{current_cart.total_items} ite#{current_cart.total_items == 1 ? 'm' : 'ns'}"
.row
	%hr
.row.logo-row
	.pull-left
		= link_to "https://www.facebook.com/704home", target: "_blank" do
			.social-network
				%span.icon-facebook
		= link_to "http://instagram.com/704home", target: "_blank" do
			.social-network
				%span.icon-instagram
		= link_to "http://www.pinterest.com/704home/inspira%C3%A7%C3%B5es/", target: "_blank" do
			.social-network
				%span.icon-pinterest
		= link_to "http://www.youtube.com/channel/UCi0KH_BZnNucvnXXZPjIbXg", target: "_blank" do
			.social-network
				%span.icon-youtube
	.align-center
		= link_to root_path do
			= image_tag "logo#{rand(1..3)}.png"
.row.menu-row
	.search_area
		= form_tag search_products_path, method: 'get' do
			= text_field_tag :search, params[:search], placeholder: "Digite sua busca"
			= button_tag(type: "submit", class: "search-button") do
				%span.icon.icon-search
		%button.search-button.color-search
			%span.icon.icon-magic

	%ul.menu-slider
		= hidden_field_tag :current, 0
		%li= link_to "Home".mb_chars.upcase.to_s, root_path
		%li
			.btn-group
				= link_to "Produtos".mb_chars.upcase.to_s, product_categories_path
				%ul.drop-menu
					- ProductCategory.all.sort_by { |x| x.name }.each do |cat|
						%li= link_to cat.name.mb_chars.upcase.to_s, cat
		%li= link_to "Quem Somos".mb_chars.upcase.to_s, about_path
		%li
			.btn-group
				-# = link_to "Ambiente".mb_chars.upcase.to_s, ambients_path
				= link_to "Ambientes".mb_chars.upcase.to_s, ambients_path
				%ul.drop-menu
					- Ambient.all.sort_by { |x| x.name }.each do |amb|
						%li= link_to amb.name.mb_chars.upcase.to_s, amb
		%li= link_to "Inspire-se".mb_chars.upcase.to_s, PostCategory.find_by_name('Inspire-se')
		%li= link_to "DIY".mb_chars.upcase.to_s, PostCategory.find_by_name('DIY')
		%li= link_to "Toques dos Experts".mb_chars.upcase.to_s, architects_path
		-# %li= link_to "Revista".mb_chars.upcase.to_s, Magazine.last
		%li= link_to "Clube 704 Home".mb_chars.upcase.to_s, club_path
		- if Press.count > 0
			%li= link_to "704 na Mídia".mb_chars.upcase.to_s, presses_path
	%hr
	.slider
.row.sub-menu-row

-# .row.color-row
-# 	- n = Math.sqrt(@colors.length).round.to_i
-# 	.color-select{style: "width: #{80 * n}px; margin-left: #{-80 * n}px"}
-# 		- counter1 = 0
-# 		- @colors.each_slice(n) do |colors|
-# 			- counter = 0
-# 			.row{ id: "color#{counter1}" }
-# 				- counter1 += 1
-# 				- colors.each do |color|
-# 					.columns{ class: "grid#{(12/n)}" }
-# 						= link_to color_search_products_path(color_id: color.id) do
-# 							.color{ style: "background-color: #{color.code};", id: "color#{counter}"}
-# 								.hover-color
-# 							- counter += 1


.row.color-row
	.color-select
		.color-box
			- @colors.each_slice(6) do |colors|
				- while colors.length < 6
					- colors.push nil
				.columns.grid1.pull-right
					- colors.each do |color|
						- if color.nil?
							.no-color
								%span X
						- else
							= link_to color_search_products_path(color_id: color.id) do
								.color{ style: "background-color: #{color.code};" }
									.hover-color
= javascript_include_tag 'header/set_facebook_connect_buttons'

app/views/shared/_img.html.haml
- photos.each_with_index do |pho, i|
	- if i < 4 or show_all
		- if pho.class == String
			= image_tag pho, class: "admin_thumb"
		- elsif pho.present?
			= image_tag pho.photo.url(:thumb), class: "admin_thumb"
	- else
		%span.extra= "(+#{photos.length - i})"
		- break

app/views/shared/_modal.html.haml
#modal.modal.hide.fade{tabindex: '-1', role: 'dialog', :'aria-labelledby' => 'myModalLabel', :'aria-hidden' => 'true'}
	%button.close{type: 'button', :'data-dismiss' => 'modal', :'aria-hidden' => 'true'}
		%p &times;
	.modal-body


#img-modal.modal.hide.fade{tabindex: '-1', role: 'dialog', :'aria-labelledby' => 'myModalLabel', :'aria-hidden' => 'true'}
	%button.close{type: 'button', :'data-dismiss' => 'modal', :'aria-hidden' => 'true'}
		%p &times;
	.modal-body

app/views/shared/_page.html.haml
= f.inputs "Página #{i.to_i + 1}", class: 'inputs page' do
	%button.remove_page Remove page
	- if page.nil?
		.page_photo
			.left
				%img
				= hidden_field_tag :photo
			.right
				.droppable_element
					= image_tag 'marker.png'
					.hover= image_tag 'marker_hover.png'
				%p Arraste para colocar referências
				= f.input :product, as: :select, collection: options_from_collection_for_select(@color_products, "id", "slug")
				= f.input :website, as: :string
	- else
		.page_photo{style: 'position: relative;'}
			.left
				= image_tag page.photo
				= hidden_field_tag "photo#{i}".to_sym, page.photo
				= f.input :product, as: :select, collection: options_from_collection_for_select(@color_products, "id", "slug")
				= f.input :website, as: :string
			.right
				.droppable_element
					= image_tag 'marker.png'
					.hover= image_tag 'marker_hover.png'
				%p Arraste para colocar referências
				- page.references.each_with_index do |ref, j|
					.droppable_element.added{style: "position: absolute;"}
						= image_tag 'marker.png'
						.hover= image_tag 'marker_hover.png'
					= hidden_field_tag "posX#{i}#{j}", ref.pos_x
					= hidden_field_tag "posY#{i}#{j}", ref.pos_y
					%li.select.input.optional{id: "magazine_product_input#{i}#{j}"}
						= label_tag "product#{i}#{j}".to_sym, "Produto #{j + 1}"
						= select_tag "product#{i}#{j}".to_sym, options_from_collection_for_select(@color_products, "id", "name", ref.product_id.to_i), prompt: ''
						%br
						= label_tag "website#{i}#{j}".to_sym, "Website #{j + 1}"
						= text_field_tag "website#{i}#{j}".to_sym, ref.website

app/views/shared/_share.html.haml
.share-bt#share-twitter
	%span.icon.icon-twitter
	Tweet
.share-bt#share-fb
	%span.icon.icon-thumbs-up
	Like
.share-bt#share-google
	%span.icon.icon-google-plus
.share-bt#share-pinterest
	%span.icon.icon-pinterest

app/views/shared/_thanks_modal.haml
#thanks-modal.modal.hide.fade{tabindex: '-1', role: 'dialog', :'aria-labelledby' => 'myModalLabel', :'aria-hidden' => 'true'}
  %button.close{type: 'button', :'data-dismiss' => 'modal', :'aria-hidden' => 'true'}
    %p &times;
  .modal-body
    .row.thanks
      .grid12.columns
        .padding40
          .title= "OBRIGADO POR COMPRAR CONOSCO"
          %hr
          %p Sua compra foi efetuada com sucesso.
          - if @payment.payment_method == 'creditCard'
            %p Seu cartão está em processo de aprovação e assim que for aprovado enviaremos seu produto.
          - elsif @payment.payment_method == 'boleto'
            %p
              Caso o seu boleto não tenha aberto automaticamente em outra aba do seu navegador, o link para acessar e imprimir é
              = link_to @payment.payment_link, @payment.payment_link, style: 'word-wrap: break-word;', target: '_blank'
            %p Assim que confirmarmos o recebimento do pagamento enviaremos seu produto.
            :javascript
              window.open("#{@payment.payment_link}")


:javascript
  $('#thanks-modal').modal();

app/views/shared/_video.html.haml
%iframe{width: "200", height: "200", src: video, frameborder: "0", allowfullscreen: nil}