config/routes.rb
Site704home::Application.routes.draw do
  get "coupons/create"

	devise_for :admin_users, ActiveAdmin::Devise.config
	ActiveAdmin.routes(self)

	devise_for :users,
	path: "",
	path_names: {
		sign_in: "login",
		sign_out: "logout",
	},
	controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"  }

	resources :product_categories, only: [:index, :show], path: 'categorias'
	resources :ambients, only: [:index, :show], path: 'ambientes' do
		resources :sub_ambients, only: [:show], path: 'subambientes'
	end

	resources :users, only: [], path: 'usuarios' do
		member do
			get 'cart', controller: 'carts', action: 'show', path: 'carrinho'
			get 'carts', controller: 'carts', action: 'index', path: 'pedidos'
			# get 'payments', controller: 'payments', action: 'index', path: 'pagamentos'
		end
	end

	resources :payments, only: [:new, :create], path: 'pagamentos'
	resources :payment_notifications, only: [:create], path: 'notificacoes_de_pagamento'

	resources :newsletters, only: [:create]

	# resources :magazines, only: [:show, :index], path: 'revistas'
	resources :magazines, only: [:show], path: 'revistas'

	resources :products, only: [], path: 'busca' do
		collection do
			get 'search'
			get 'color_search'
		end
	end

	resources :color_products, only: [:show], path: 'produtos' do
		resources :cart_color_products, only: [:index, :create, :update, :destroy]
	end

	resources :post_categories, only: [:show]
	resources :posts, only: [:show]

	resources :year, only: [] do
		resources :month, only: [] do
			resources :calendar, only: [:show]
		end
	end

	resources :architects, only: [:show, :index], path: 'arquitetos'

	resources :carts, only: [:show], path: 'carrinho' do
		member do
			resources :coupons, only: [:create], path: 'cupons'
		end
	end

	get 'quem_somos', controller: 'static_pages', action: 'about', path: 'quem_somos', as: :about
	get 'termos_de_privacidade', controller: 'static_pages', action: 'privacy', path: 'termos_de_privacidade', as: :privacy
	get 'politica_de_troca', controller: 'static_pages', action: 'trade', path: 'politica_de_troca', as: :trade
	get 'clube', controller: 'static_pages', action: 'club', path: 'clube', as: :club
	get 'faq', controller: 'static_pages', action: 'faq', path: 'faq', as: :faq
	get 'regulamento_promocional', controller: 'static_pages', action: 'promotion_rules', as: :promotion_rules

	match 'contact' => 'contact#create', as: :contact, via: :post
	resource :comments, only: [:create]

	resources :collections, only: [:show], path: 'colecoes'

	resources :multibrands, only: [:new, :create], path: 'multimarcas'
	resources :b2bs, only: [:new, :create], path: 'b2b'
	resources :presses, only: [:index, :show], path: '704-na-midia'

	# resources :magazine_pages, only: [:create]

	root to: 'static_pages#home'
	# root to: 'static_pages#building'
	match 'home' => 'static_pages#home', as: :home, via: :get

	get 'sitemap' => 'sitemap#index', as: :sitemap

	get 'obrigado' => 'static_pages#home', as: :thanks, via: :get

	resources :shipping, only: [:create], controller: 'carts/shipping'

	namespace :api do
		namespace :v1 do
			resources :products, only: [:create, :update, :index, :show]
			resources :colors, only: [:create, :update, :index, :show]
			resources :color_products, only: [:create, :update, :index, :show]
			resources :payments, only: [:index, :show] do
				member do
					put 'sync'
					put 'set_shipping_code'
				end
				collection do
					get 'no_shipping_code'
				end
			end
		end
	end
end

app/models/cart.rb
# encoding: UTF-8

class Cart < ActiveRecord::Base
	attr_accessible :payment_date

	belongs_to :user
	has_many :cart_color_products
	has_many :payment_notifications

	validate :validate_user_has_no_open_carts, on: :create

  belongs_to :promotion

  has_many :payments

  default_scope { includes(:cart_color_products) }

  def full_total_price
    self.total_price.to_f + self.shipping
  end

	def total_price
		self.total_price_no_discount - self.discount
	end

  def total_price_no_discount
    cart_color_products.to_a.sum(&:total_price)
  end

  def discount
    self.promotion.present? ? self.promotion.absolute_advantage.amount : 0
  end

  def shipping
    if self.shipping_cost
      self.shipping_cost / 100.0
    else
      self.final_payment ? self.final_payment.shipping_cost : 0
    end
  end

  def final_payment
    self.payments.last
  end

  def total_items
    self.cart_color_products.map { |x| x.ammount }.sum
  end

	def pagseguro_pay notification_url, redirect_url
		return nil if self.cart_color_products.empty?

    payment = PagSeguro::PaymentRequest.new
    payment.shipping = PagSeguro::Shipping.new
    payment.shipping.cost = self.shipping

		payment.reference = self.id
		payment.notification_url = notification_url
		payment.redirect_url = redirect_url
    payment.max_age = 1200

		self.cart_color_products.each do |ccp|
			payment.items << {
				id: ccp.color_product.id,
				description: ccp.color_product.humanized_name,
				amount: ccp.color_product.product.price.to_f,
				quantity: ccp.ammount
			}
		end

    payment.extra_amount = -self.discount

		return payment.register
	end

  def closed?
    (self.payments.any? or self.payment_date.present?) ? true : false
	end

	def merge cart
		if cart.class == Cart
      cp_ids = self.cart_color_products.map { |x| x.color_product_id }
      cart.cart_color_products.each do |ccp|
        if cp_ids.include? ccp.color_product_id
          sccp = self.cart_color_products.where(color_product_id: ccp.color_product_id).limit(1).first
          sccp.ammount = sccp.ammount + ccp.ammount
          sccp.save
        else
          self.cart_color_products.push(ccp)
          self.save
        end
      end
      cart.reload
      cart.destroy
    else
      raise "Carrinho deve ser da classe Cart"
    end
	end

  def self.cleanup
    where(['updated_at < ? AND user_id IS NULL', 12.hours.ago]).find_each(&:destroy)
  end

  def clean
    any_clean = false

    self.cart_color_products.each do |cpp|
      if cpp.color_product.nil? or cpp.color_product.stock_ammount < cpp.ammount
        cpp.destroy
        any_clean = true
      end
    end

    any_clean
  end

  def to_shipping_package
    package = Correios::Frete::Pacote.new

    self.cart_color_products.each do |ccp|
      ccp.ammount.times do
        package.adicionar_item ccp.to_pacote_item
      end
    end

    package
  end

  def get_shipping_price zip_code
    zip_code = BrZipCode.formatted(zip_code).gsub('.', '')

    s = Correios::Frete::Calculador.new cep_origem: '22451-090', cep_destino: zip_code, encomenda: self.to_shipping_package

    s.calcular(:pac)
  end

	private

		def validate_user_has_no_open_carts
			if self.user.present?
				if Cart.where(user_id: user_id, payment_date: nil).includes(:payments).where(payments: { cart_id: nil }).limit(1).present?
					errors.add :cart, "já está aberto."
				end
			end
		end

end

app/controllers/carts/shipping_controller.rb
# encoding: UTF-8

class Carts::ShippingController < ApplicationController
  respond_to :js

  def index
    zip_code = params[:cart][:shipping_zip_code]
    if BrZipCode.strip zip_code
      get_cart.get_shipping_prices(zip_code)

      render json: { shipping_methods: get_cart.shipping_options_hash.to_json.html_safe, zip_code: params[:cart][:zip_code] }
    else
      get_cart.shipping_options_hash = nil
      get_cart.shipping_zip_code = nil
      get_cart.save
      render json: { message: 'CEP inválido.' }, status: :unprocessable_entity
    end
  end

  def create
    zip_code = params[:cart][:shipping_zip_code]

    if BrZipCode.strip zip_code
      s = current_cart.get_shipping_price zip_code

      if s.erro == '0'
        current_cart.update_attribute(:shipping_cost, (s.valor * 100).to_i)
        current_cart.reload

        v = s.valor
        v = v.to_s.split('.')
        v[-1] = v[-1].ljust(2, '0')
        v = "R$ #{v.join(',')}"

        total = current_cart.full_total_price
        total = total.to_s.split('.')
        total[-1] = total[-1].ljust(2, '0')
        total = "R$ #{total.join(',')}"

        render json: {
          shipping: {
            value: v,
            days: s.prazo_entrega,
            name: 'PAC'
          },
          cart: {
            total: total
          }
        }
      else
        render json: {
          status: 'error',
          message: 'Houve algum erro no cálculo do frete com o CEP informado. Verifique se o CEP está correto.'
        }
      end
    end
    # method = get_cart.shipping_options_hash.select { |x| x.codigo == params[:cart][:shipping_method] }.first

    # if method
    #   get_cart.shipping_hash = method
    #   unless get_cart.save
    #     render json: { message: "Ocorreu algum erro. Tente novamente ou entre em contato em (21) 2523-1146." }, status: :unprocessable_entity
    #   else
    #     flash.now[:success] = "Forma de entrega escolhido com sucesso."
    #   end
    # else
    #   render json: { message: 'Método de entrega inválido.' }, status: :unprocessable_entity
    # end
  end
end

app/controllers/carts_controller.rb
# encoding: UTF-8

class CartsController < ApplicationController
  def index
    @carts = current_user.carts.includes(:payments).where('payment_date IS NOT NULL OR payments.cart_id IS NOT NULL').order('carts.created_at DESC')
  end

	def show
		@cart = current_cart
    if @cart.cart_color_products.empty?
      flash[:error] = "O seu carrinho está vazio."
      redirect_to root_path
    end
	end
end

app/views/carts/index.html.haml
.row
  .title Meus pedidos
%hr
.row
  .grid12.columns.carts-index
    - if @carts.empty?
      %p Você não possui nenhum pedido.
    - else
      %table
        %thead
          %tr
            %th Data do Pagamento
            %th Data do Fechamento
            %th Tracking ID
        %tbody
          - @carts.each do |cart|
            %tr
              %td= cart.payment_date ? cart.payment_date.strftime('%d/%m/%Y às %H:%M') : 'Aguardando confirmação do pagamento'
              %td
                - if cart.payments.any?
                  = cart.payments.last.created_at.strftime('%d/%m/%Y às %H:%M')
                - elsif cart.payment_date.present?
                  = cart.payment_date.strftime('%d/%m/%Y às %H:%M')
              %td
                - if cart.shipping_code.nil?
                  = "Seu pedido está sendo processado."
                - else
                  = link_to "Acompanhar Pedido", "http://www.jall.com.br/web/rastreamento.jsp?contrato= 4071&cliente= 3150&num_enc_cli=#{cart.shipping_code}", target: '_blank'

app/views/carts/show.html.haml
- title("Meu carrinho", true)

.row
	.title Carrinho
%hr
.row
	%table.cart
		- @cart.cart_color_products.each do |cp|
			%tr{data: { id: cp.id }}
				%td= image_tag cp.color_product.photo.photo.url(:home_thumb)
				%td= link_to cp.color_product.humanized_name, cp.color_product
				%td
					- unless cp.ammount < 2
						= link_to color_product_cart_color_products_path(color_product_id: cp.color_product_id, ammount: -1), method: :post, class: 'ammount-changer' do
							%span.icon.icon-minus-sign
					- else
						%span.icon.icon-minus-sign.disabled-icon
					%span= "#{cp.ammount} #{cp.ammount == 1 ? 'unidade' : 'unidades'}"
					= link_to color_product_cart_color_products_path(color_product_id: cp.color_product_id, ammount: 1), method: :post, class: 'ammount-changer' do
						%span.icon.icon-plus-sign
				%td.ammount
					%span= "#{number_to_currency(cp.unit_price * cp.ammount)}"
				%td.delete
					= link_to 'excluir', color_product_cart_color_product_path(cp.color_product, cp), method: :delete, class: 'delete_from_cart'
					.bg
.row.total.discount-price
	%span= "Desconto ".mb_chars.upcase.to_s
	%span.total_price= "#{number_to_currency(@cart.discount)}"
-# .row.total.discount-price
-# 	%span= "Frete ".mb_chars.upcase.to_s
-# 	%span.total_price= "#{number_to_currency(@cart.shipping)}"
.row.total
	%span= "Total ".mb_chars.upcase.to_s
	%span.total_price= "#{number_to_currency(@cart.total_price + @cart.shipping)}"
.row.continue
	.row.buy
		= semantic_form_for Coupon.new do |f|
			= f.submit "Adicionar cupom", class: 'buy_bt'
			= f.input :code
- if user_signed_in?
	- if current_user.cpf.present?
		.row.continue
			= link_to 'Continuar comprando', product_categories_path, class: 'buy_bt'
		.row.buy
			-# = semantic_form_for current_user, url: payments_path, method: :post, remote: true, html: { id: 'buy-bt-form' } do |f|
			-# 	= f.submit 'Finalizar compra', class: 'buy_bt yellow-button'
			-# 	%label.gift Para presente?
			-# 	%input.gift{ type: "checkbox", name: "gift", id: "gift", checked: current_user.active_cart.gift }
			= link_to 'Finalizar compra', new_payment_path, class: 'buy_bt yellow-button'
		-# .row.advice
		-# 	= image_tag 'buy-pagseguro.png'
	- else
		.row.continue
			= link_to 'Continuar comprando', product_categories_path, class: 'buy_bt'
		.row.buy
			= link_to 'Completar cadastro', edit_user_registration_path(after_login_path: request.url), :class => 'modal-render-link buy_bt', remote: true
		.row.advice
			= image_tag 'no-cpf.png'
- else
	.row.continue
		= link_to 'Continuar comprando', product_categories_path, class: 'buy_bt'
	.row
		-# = link_to 'Login / Cadastrar', new_user_registration_path(after_login_path: request.url), :class => 'login-to-buy modal-render-link', remote: true
		= link_to 'Finalizar compra', new_user_registration_path(after_login_path: new_payment_path, after_login_method: 'get'), :class => 'login-to-buy modal-render-link yellow-button', remote: true
	.row.advice
		= image_tag 'login-to-buy.png'

- if params[:after_login_path].present? and params[:after_login_method] == 'post'
	:javascript
		$(document).ready(function() {
			$('form#buy-bt-form').find('.buy_bt.yellow-button').click();
		});